title: Infectious Diseases Toolkit
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: Infectious Diseases Toolkit
# this appears on the top navigation bar next to the home button

description: "Find the answers to your Research Data Management questions in Life Sciences."
# Metadata description of the website

# gtag: G-RXQ55EFTTH
# Google analytics tag

remote_theme: ELIXIR-Belgium/jekyll-bootstrap-theme@1.0.0

theme_variables:
  theme_color: da366e
  fonts:
    - https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename:output_ext
      layout: "page"
      sidebar: main

